### ISSUE TITLE
android sharedlibrary

### ISSUE THREAD

**Issue by qinhuangran** [george012/libhv-build#2]
大佬，你好，android 各种abi库可以build出来了没

**Comment by george012** [comment]
正在搞，最近太忙，还没弄出来

**Comment by george012** [comment]
Android搞定arme-v7a，arm-v8a，x86，x86_x64，都有

**Comment by qinhuangran** [comment]
能否上传一下这些arme-v7a，arm-v8a，x86，x86_x64的so库么，我编出来的集成引用报错：
java.lang.UnsatisfiedLinkError: dlopen failed: library "../jniLibs/arm64-v8a/libhv.so" not found
