### ISSUE TITLE
能否上传一下这些arme-v7a，arm-v8a，x86，x86_x64的so库么，我编出来的集成引用报错：

### ISSUE THREAD

**Issue by qinhuangran** [george012/libhv-build#3]
能否上传一下这些arme-v7a，arm-v8a，x86，x86_x64的so库么，我编出来的集成引用报错：
java.lang.UnsatisfiedLinkError: dlopen failed: library "../jniLibs/arm64-v8a/libhv.so" not found

_Originally posted by @qinhuangran in https://github.com/george012/libhv-build/issues/2#issuecomment-1565552642_

**Comment by george012** [comment]
jniLibs/arm64-v8a/libhv.so 你需要 文件夹区分？  而 libhv.so 作为同意的 so库的名字

**Comment by george012** [comment]
已经在 release里面 有自动编译好的
![image](https://github.com/george012/libhv-build/assets/5527399/6db74111-a315-4474-9b4c-79a71e865026)

**Comment by george012** [comment]
已经按照默认集成配置更改了目录，欢迎测试
![image](https://github.com/george012/libhv-build/assets/5527399/8941404f-76c2-4ba4-825b-a3d11e773b31)

**Comment by george012** [comment]
![image](https://github.com/george012/libhv-build/assets/5527399/ab5037ab-8bac-4cf7-9b5c-754a3c5785aa)
